CREATE TABLE IF NOT EXISTS TB_PAIS (
	CODIGO SERIAL NOT NULL,
	NOME VARCHAR(80),
	CONSTRAINT PK_PAIS PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_ESTADO (
	CODIGO SERIAL NOT NULL,
	ID_PAIS INTEGER NOT NULL,
	NOME VARCHAR(80),
	CONSTRAINT PK_ESTADO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_PAIS FOREIGN KEY(ID_PAIS) REFERENCES TB_PAIS(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_CIDADE (
	CODIGO SERIAL NOT NULL,
	ID_ESTADO INTEGER NOT NULL,
	NOME VARCHAR(85) NOT NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY(CODIGO),
	CONSTRAINT FK_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES TB_ESTADO(CODIGO)
);
