DROP TABLE IF EXISTS TB_PESSOA CASCADE;

CREATE TABLE IF NOT EXISTS TB_PESSOA (
	CODIGO SERIAL NOT NULL,
	ID_TIPO_PESSOA INTEGER NOT NULL, 
	NOME VARCHAR(85) NOT NULL UNIQUE,
	IS_INSTITUICAO_FINANCEIRA BOOLEAN NULL,
	IS_ATIVO BOOLEAN NOT NULL,
	CONSTRAINT PK_PESSOA PRIMARY KEY(CODIGO),
	CONSTRAINT FK_TIPO_PESSOA FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TB_TIPO_PESSOA(CODIGO)
);

CREATE SEQUENCE SEQ_PESSOA START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_PESSOA.CODIGO;

INSERT INTO TB_PESSOA (CODIGO, ID_TIPO_PESSOA, NOME, IS_INSTITUICAO_FINANCEIRA, IS_ATIVO) VALUES 
(NEXTVAL('SEQ_PESSOA'), (SELECT CODIGO FROM TB_TIPO_PESSOA WHERE LOWER(SIGLA) LIKE LOWER('PF')), 'José Quintinn', FALSE, TRUE),
(NEXTVAL('SEQ_PESSOA'), (SELECT CODIGO FROM TB_TIPO_PESSOA WHERE LOWER(SIGLA) LIKE LOWER('PJ')), 'Brava Fibra Internet', TRUE, TRUE),
(NEXTVAL('SEQ_PESSOA'), (SELECT CODIGO FROM TB_TIPO_PESSOA WHERE LOWER(SIGLA) LIKE LOWER('PJ')), 'Banco Caixa Econômica Federal', TRUE, TRUE),
(NEXTVAL('SEQ_PESSOA'), (SELECT CODIGO FROM TB_TIPO_PESSOA WHERE LOWER(SIGLA) LIKE LOWER('PJ')), 'Banco Santander', TRUE, TRUE);