DROP TABLE IF EXISTS TB_TIPO_CONTRATO CASCADE;

CREATE TABLE IF NOT EXISTS TB_TIPO_CONTRATO (
	CODIGO SERIAL NOT NULL,
	DESCRICAO VARCHAR(85) NOT NULL,
	CONSTRAINT PK_TIPO_CONTRATO PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE SEQ_TIPO_CONTRATO START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_TIPO_CONTRATO.CODIGO;

INSERT INTO TB_TIPO_CONTRATO (CODIGO, DESCRICAO) VALUES 
(NEXTVAL ('SEQ_TIPO_CONTRATO'), 'Contrato de Conta Bancária'),
(NEXTVAL ('SEQ_TIPO_CONTRATO'), 'Contrato de Trabalho CLT'),
(NEXTVAL ('SEQ_TIPO_CONTRATO'), 'Contrato de Trabalho CNPJ'),
(NEXTVAL ('SEQ_TIPO_CONTRATO'), 'Contrato de Internet'),
(NEXTVAL ('SEQ_TIPO_CONTRATO'), 'Contrato de Benefício (Seguro Desemprego)'),
(NEXTVAL ('SEQ_TIPO_CONTRATO'), 'Contrato de Benefício (Auxílio Doença)'),
(NEXTVAL ('SEQ_TIPO_CONTRATO'), 'Contrato de Benefício (INSS Saúde)');