CREATE TABLE IF NOT EXISTS TB_TIPO_CONTRATO (
	CODIGO SERIAL NOT NULL,
	DESCRICAO VARCHAR(65) NOT NULL,
	CONSTRAINT PK_TIPO_CONTRATO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_CONTRATO (
	CODIGO SERIAL NOT NULL,
	ID_TIPO_CONTRATO INTEGER NOT NULL,
	ID_PESSOA_CONTRATANTE INTEGER NOT NULL,
	ID_PESSOA_CONTRATADO INTEGER NOT NULL,
	INICIO_VIGENCIA DATE NOT NULL,
	FIM_VIGENCIA DATE NULL,
	IS_ATIVO BOOLEAN NOT NULL,
	CONSTRAINT PK_CONTRATO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_TIPO_CONTRATO FOREIGN KEY (ID_TIPO_CONTRATO) REFERENCES TB_PESSOA (CODIGO),
	CONSTRAINT FK_PESSOA_CONTRATANTE FOREIGN KEY (ID_PESSOA_CONTRATANTE) REFERENCES TB_PESSOA (CODIGO),
	CONSTRAINT FK_PESSOA_CONTRATADO FOREIGN KEY (ID_PESSOA_CONTRATADO) REFERENCES TB_PESSOA (CODIGO)
);
