DROP TABLE IF EXISTS TB_PARCELAMENTO CASCADE;

CREATE TABLE IF NOT EXISTS TB_PARCELAMENTO (
	CODIGO SERIAL NOT NULL,
	ID_RECEITA INTEGER NOT NULL,
	DATA_PAGAMENTO_PARCELA DATE NULL, 
	DATA_VENCIMENTO_PARCELA DATE NOT NULL, 
	SITUACAO_PAGAMENTO VARCHAR(45) NOT NULL, 
	NUMERO_PARCELA INTEGER NOT NULL, 
	VALOR_PREVISTO_PARCELA FLOAT8 NOT NULL,
	VALOR_PAGAMENTO_PARCELA FLOAT8 NULL,
	VALOR_TOTAL_PARCELAMENTO FLOAT8 NOT NULL,
	CONSTRAINT PK_PARCELAMENTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_RECEITA FOREIGN KEY (ID_RECEITA) REFERENCES TB_RECEITA (CODIGO)
);

CREATE SEQUENCE SEQ_PARCELAMENTO START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_PARCELAMENTO.CODIGO;

INSERT INTO PUBLIC.TB_PARCELAMENTO (CODIGO, ID_RECEITA, DATA_VENCIMENTO_PARCELA, SITUACAO_PAGAMENTO, NUMERO_PARCELA, DATA_PAGAMENTO_PARCELA, VALOR_PREVISTO_PARCELA, VALOR_PAGAMENTO_PARCELA, VALOR_TOTAL_PARCELAMENTO) VALUES
(NEXTVAL ('SEQ_PARCELAMENTO'), (SELECT codigo FROM TB_RECEITA WHERE identificador LIKE 'REC20210313001FIX'), '2021-02-14', 'PENDENTE', 1, NULL, 2000.0, NULL, 9500.0),
(NEXTVAL ('SEQ_PARCELAMENTO'), (SELECT codigo FROM TB_RECEITA WHERE identificador LIKE 'REC20210313001FIX'), '2021-03-14', 'PENDENTE', 2, NULL, 2000.0, NULL, 9500.0),
(NEXTVAL ('SEQ_PARCELAMENTO'), (SELECT codigo FROM TB_RECEITA WHERE identificador LIKE 'REC20210313001FIX'), '2021-04-14', 'PENDENTE', 3, NULL, 2000.0, NULL, 9500.0),
(NEXTVAL ('SEQ_PARCELAMENTO'), (SELECT codigo FROM TB_RECEITA WHERE identificador LIKE 'REC20210313001FIX'), '2021-05-14', 'PENDENTE', 4, NULL, 2000.0, NULL, 9500.0),
(NEXTVAL ('SEQ_PARCELAMENTO'), (SELECT codigo FROM TB_RECEITA WHERE identificador LIKE 'REC20210313001FIX'), '2021-06-14', 'PENDENTE', 5, NULL, 2000.0, NULL, 9500.0);
