DROP TABLE IF EXISTS TB_CATEGORIA_CARTAO_BANCARIO CASCADE;

CREATE TABLE IF NOT EXISTS TB_CATEGORIA_CARTAO_BANCARIO(
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(90) NOT NULL,
    CONSTRAINT PK_TIPO_CARTAO_BANCARIO PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE SEQ_TIPO_CARTAO_BANCARIO START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_CATEGORIA_CARTAO_BANCARIO.CODIGO;

INSERT INTO TB_CATEGORIA_CARTAO_BANCARIO (CODIGO, DESCRICAO) VALUES (NEXTVAL('SEQ_TIPO_CARTAO_BANCARIO'), 'Cartão de Crédito'), (NEXTVAL('SEQ_TIPO_CARTAO_BANCARIO'), 'Cartão de Débito'), (NEXTVAL('SEQ_TIPO_CARTAO_BANCARIO'), 'Cartão de Benefício');