DROP TABLE IF EXISTS TB_BANDEIRA_CARTAO_BANCARIO CASCADE;

CREATE TABLE IF NOT EXISTS TB_BANDEIRA_CARTAO_BANCARIO(
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(90) NOT NULL,
    CONSTRAINT PK_BANDEIRA PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE SEQ_BANDEIRA START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_BANDEIRA_CARTAO_BANCARIO.CODIGO;

INSERT INTO TB_BANDEIRA_CARTAO_BANCARIO (CODIGO, DESCRICAO) VALUES (NEXTVAL('SEQ_BANDEIRA'), 'Master Card'), (NEXTVAL('SEQ_BANDEIRA'), 'Visa Card');