DROP TABLE IF EXISTS TB_FUNCAO_CARTAO_BANCARIO CASCADE;

CREATE TABLE IF NOT EXISTS TB_FUNCAO_CARTAO_BANCARIO(
	CODIGO SERIAL NOT NULL,
	ID_CARTAO_BANCARIO INTEGER NOT NULL,
	DESCRICAO VARCHAR(90) NOT NULL,
	IS_ATIVO BOOLEAN NOT NULL,
	CONSTRAINT PK_FUNCAO_CARTAO_BANCARIO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_CARTAO_BANCARIO FOREIGN KEY (ID_CARTAO_BANCARIO) REFERENCES TB_CARTAO_BANCARIO (CODIGO)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_FUNCAO_CARTAO_BANCARIO START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_FUNCAO_CARTAO_BANCARIO.CODIGO;

INSERT INTO TB_FUNCAO_CARTAO_BANCARIO (CODIGO, ID_CARTAO_BANCARIO, DESCRICAO, IS_ATIVO) VALUES
(NEXTVAL('SEQ_FUNCAO_CARTAO_BANCARIO'), (SELECT CODIGO FROM TB_CARTAO_BANCARIO WHERE DATA_VALIDADE = '10/28'), 'CRÉDITO', TRUE),
(NEXTVAL('SEQ_FUNCAO_CARTAO_BANCARIO'), (SELECT CODIGO FROM TB_CARTAO_BANCARIO WHERE NOME_IMPRESSO = 'JOSE Q S JUNIOR'), 'DÉBITO', TRUE);