DROP TABLE IF EXISTS TB_CONTRATO CASCADE;

CREATE TABLE IF NOT EXISTS TB_CONTRATO (
	CODIGO SERIAL NOT NULL,
	ID_TIPO_CONTRATO INTEGER NOT NULL,
	ID_PESSOA_CONTRATANTE INTEGER NOT NULL, 
	ID_PESSOA_CONTRATADO INTEGER NOT NULL,
	DATA_INICIO_VIGENCIA DATE NULL,
	DATA_FIM_VIGENCIA DATE NULL,
	IS_ATIVO BOOLEAN NOT NULL,
	CONSTRAINT PK_CONTRATO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_TIPO_CONTRATO FOREIGN KEY (ID_TIPO_CONTRATO) REFERENCES TB_TIPO_CONTRATO (CODIGO),
	CONSTRAINT FK_PESSOA_CONTRATANTE FOREIGN KEY (ID_PESSOA_CONTRATANTE) REFERENCES TB_PESSOA (CODIGO),
	CONSTRAINT FK_PESSOA_CONTRATADO FOREIGN KEY (ID_PESSOA_CONTRATADO) REFERENCES TB_PESSOA (CODIGO)
);

CREATE SEQUENCE SEQ_CONTRATO START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_CONTRATO.CODIGO;

INSERT INTO TB_CONTRATO (CODIGO, ID_TIPO_CONTRATO, ID_PESSOA_CONTRATADO, ID_PESSOA_CONTRATANTE, DATA_INICIO_VIGENCIA, DATA_FIM_VIGENCIA, IS_ATIVO) VALUES 
(NEXTVAL('SEQ_CONTRATO'), (SELECT CODIGO FROM TB_TIPO_CONTRATO WHERE LOWER(DESCRICAO) LIKE LOWER('Contrato de Conta Bancária')), (SELECT CODIGO FROM TB_PESSOA WHERE upper(NOME) LIKE upper('%Banco Santander%')), (SELECT CODIGO FROM TB_PESSOA WHERE upper(NOME) LIKE upper('%JOSÉ QUINTIN%')), NULL, NULL, TRUE),
(NEXTVAL('SEQ_CONTRATO'), (SELECT CODIGO FROM TB_TIPO_CONTRATO WHERE LOWER(DESCRICAO) LIKE LOWER('Contrato de Conta Bancária')), (SELECT CODIGO FROM TB_PESSOA WHERE upper(NOME) LIKE upper('%Banco Caixa Econômica Federal%')), (SELECT CODIGO FROM TB_PESSOA WHERE upper(NOME) LIKE upper('%JOSÉ QUINTIN%')), NULL, NULL, TRUE),
(NEXTVAL('SEQ_CONTRATO'), (SELECT CODIGO FROM TB_TIPO_CONTRATO WHERE LOWER(DESCRICAO) LIKE LOWER('Contrato de Benefício (Seguro Desemprego)')), (SELECT CODIGO FROM TB_PESSOA WHERE upper(NOME) LIKE upper('%Banco Caixa Econômica Federal%')), (SELECT CODIGO FROM TB_PESSOA WHERE upper(NOME) LIKE upper('%JOSÉ QUINTIN%')), '2021-02-14', '2021-06-14', TRUE);
