DROP TABLE IF EXISTS TB_CONTA_BANCARIA CASCADE;

CREATE TABLE IF NOT EXISTS TB_CONTA_BANCARIA (
	CODIGO SERIAL NOT NULL,
	ID_TIPO_CONTA_BANCARIA INTEGER NOT NULL,
	ID_CONTRATO INTEGER NOT NULL,
	NUMERO_AGENCIA VARCHAR(45) NOT NULL UNIQUE,
	NUMERO_CONTA VARCHAR(45) UNIQUE,
	DATA_ABERTURA DATE NULL,
	DATA_ENCERRAMENTO DATE NULL,
	VALOR_SALDO_INICIAL FLOAT NOT NULL,
	CONSTRAINT PK_CONTA_BANCARIA PRIMARY KEY (CODIGO),
	CONSTRAINT FK_TIPO_CONTA_BANCARIA FOREIGN KEY (ID_TIPO_CONTA_BANCARIA) REFERENCES TB_TIPO_CONTA_BANCARIA(CODIGO),
	CONSTRAINT FK_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES TB_CONTRATO(CODIGO)
);

CREATE SEQUENCE SEQ_CONTA_BANCARIA START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_CONTA_BANCARIA.CODIGO;

INSERT INTO TB_CONTA_BANCARIA (CODIGO, ID_TIPO_CONTA_BANCARIA, ID_CONTRATO, NUMERO_AGENCIA, NUMERO_CONTA, DATA_ABERTURA, DATA_ENCERRAMENTO, VALOR_SALDO_INICIAL) VALUES
(NEXTVAL ('SEQ_CONTA_BANCARIA'), (SELECT CODIGO FROM TB_TIPO_CONTA_BANCARIA WHERE LOWER(DESCRICAO) LIKE LOWER('CONTA CORRENTE')), 1, '3441', '01083366-1', NULL, NULL, 0);