DROP TABLE IF EXISTS TB_CATEGORIA_RECEITA CASCADE;

CREATE TABLE IF NOT EXISTS TB_CATEGORIA_RECEITA (
	CODIGO SERIAL NOT NULL,
	DESCRICAO VARCHAR(90) NOT NULL UNIQUE,
	CONSTRAINT PK_CATEGORIA_RECEITA PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE SEQ_CATEGORIA_RECEITA START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_CATEGORIA_RECEITA.CODIGO;

INSERT INTO TB_CATEGORIA_RECEITA (CODIGO, DESCRICAO) VALUES
(NEXTVAL('SEQ_CATEGORIA_RECEITA'), 'Devolução de Empréstimo (Concessão)'),
(NEXTVAL('SEQ_CATEGORIA_RECEITA'), 'Solicitação de Empréstimo (Obtenção)'),
(NEXTVAL('SEQ_CATEGORIA_RECEITA'), 'Pagamento de Salário Mensalista'),
(NEXTVAL('SEQ_CATEGORIA_RECEITA'), 'Benefício (Seguro Desemprego)');