DROP TABLE IF EXISTS TB_BANDEIRA CASCADE;

CREATE TABLE IF NOT EXISTS TB_BANDEIRA(
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(90) NOT NULL,
    CONSTRAINT PK_BANDEIRA PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE SEQ_BANDEIRA START 1 INCREMENT 1 MINVALUE 1 OWNED BY TB_BANDEIRA.CODIGO;

INSERT INTO TB_BANDEIRA (CODIGO, DESCRICAO) VALUES (NEXTVAL('SEQ_BANDEIRA'), 'Master Card'), (NEXTVAL('SEQ_BANDEIRA'), 'Visa Card');